// <auto-generated />
using System;
using Cms.DataNpg.Legal.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Cms.Legal.Web.Migrations
{
    [DbContext(typeof(LegalDbContext))]
    partial class LegalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AddressUser", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_address");

                    b.Property<bool>("IsBlock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_block");

                    b.Property<bool>("IsSetDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_set_default");

                    b.Property<int>("RegionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("regions_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionsId"));

                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StateId"));

                    b.Property<string>("TitleAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_address");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Code")
                        .HasName("address_user_pkey");

                    b.ToTable("address_user", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique();

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CodeUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FisrtName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique();

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Association", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("character varying")
                        .HasColumnName("abbreviation");

                    b.Property<int?>("ActiveStatus")
                        .HasColumnType("integer")
                        .HasColumnName("active_status");

                    b.Property<string>("ActiveTitle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("active_title");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country_name");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EstablishedDate")
                        .HasColumnType("date")
                        .HasColumnName("established_date");

                    b.Property<string>("LegalAuthority")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("legal_authority");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("province_name");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website");

                    b.HasKey("Code")
                        .HasName("associations_pkey");

                    b.ToTable("associations", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Category", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<bool>("IsShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_show");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("TypeField")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type_field");

                    b.Property<string>("TypeView")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_view");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.Property<string>("ValueField")
                        .HasColumnType("text")
                        .HasColumnName("value_field");

                    b.HasKey("Code")
                        .HasName("category_pkey");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.CategoryLawyer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("LawyerCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lawyer_code");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_code");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Code", "LawyerCode", "CategoryCode")
                        .HasName("category_lawyer_pkey");

                    b.HasIndex(new[] { "CategoryCode" }, "IX_category_lawyer_category_code");

                    b.ToTable("category_lawyer", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.CertificatesLawyer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("LawyerCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lawyer_code");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("issued_by");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Code", "LawyerCode")
                        .HasName("certificates_pkey");

                    b.HasIndex(new[] { "LawyerCode" }, "IX_certificates_lawyer_lawyer_code");

                    b.ToTable("certificates_lawyer", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Chatai", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("AppName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("app_name");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("DeviceUser")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("device_user");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("IpUser")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ip_user");

                    b.Property<string>("NickName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nick_name");

                    b.Property<string>("RoleUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_user");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Code")
                        .HasName("chatai_pkey");

                    b.ToTable("chatai", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("'2014-01-01 12:01:01'::timestamp without time zone");

                    b.Property<short>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("flag");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Native")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("native");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("state_code");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id");

                    b.Property<string>("Timezone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("timezone")
                        .HasComment("IANA timezone identifier (e.g., America/New_York)");

                    b.Property<string>("Translations")
                        .HasColumnType("text")
                        .HasColumnName("translations");

                    b.Property<string>("Type")
                        .HasMaxLength(191)
                        .HasColumnType("character varying(191)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wikiDataId")
                        .HasComment("Rapid API GeoDB Cities");

                    b.HasKey("Id")
                        .HasName("cities_pkey");

                    b.HasIndex(new[] { "CountryId" }, "cities_country_id_idx");

                    b.HasIndex(new[] { "StateId" }, "cities_state_id_idx");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Contentchatai", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("ContentChat")
                        .HasColumnType("text")
                        .HasColumnName("content_chat");

                    b.Property<string>("LogchataiCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logchatai_code");

                    b.Property<DateTime?>("ReceiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receive_at");

                    b.Property<string>("ReceiveChat")
                        .HasColumnType("text")
                        .HasColumnName("receive_chat");

                    b.Property<DateTime?>("SendAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_at");

                    b.HasKey("Code")
                        .HasName("contentchatai_pkey");

                    b.ToTable("contentchatai", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Capital")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("capital");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("currency_name");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("currency_symbol");

                    b.Property<string>("Emoji")
                        .HasMaxLength(191)
                        .HasColumnType("character varying(191)")
                        .HasColumnName("emoji");

                    b.Property<string>("EmojiU")
                        .HasMaxLength(191)
                        .HasColumnType("character varying(191)")
                        .HasColumnName("emojiU");

                    b.Property<short>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("flag");

                    b.Property<long?>("Gdp")
                        .HasColumnType("bigint")
                        .HasColumnName("gdp");

                    b.Property<string>("Iso2")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso2")
                        .IsFixedLength();

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("iso3")
                        .IsFixedLength();

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nationality");

                    b.Property<string>("Native")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("native");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("numeric_code")
                        .IsFixedLength();

                    b.Property<string>("Phonecode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("phonecode");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint")
                        .HasColumnName("population");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("region");

                    b.Property<long?>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.Property<string>("Subregion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subregion");

                    b.Property<long?>("SubregionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subregion_id");

                    b.Property<string>("Timezones")
                        .HasColumnType("text")
                        .HasColumnName("timezones");

                    b.Property<string>("Tld")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tld");

                    b.Property<string>("Translations")
                        .HasColumnType("text")
                        .HasColumnName("translations");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wikiDataId")
                        .HasComment("Rapid API GeoDB Cities");

                    b.HasKey("Id")
                        .HasName("countries_pkey");

                    b.HasIndex(new[] { "RegionId" }, "countries_region_id_idx");

                    b.HasIndex(new[] { "SubregionId" }, "countries_subregion_id_idx");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.EducationsLawyer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("degree");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Institution")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("institution");

                    b.Property<string>("LawyerCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lawyer_code");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Code")
                        .HasName("educations_lawyer_pkey");

                    b.HasIndex(new[] { "LawyerCode" }, "IX_educations_lawyer_lawyer_code");

                    b.ToTable("educations_lawyer", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.ExperiencesLawyer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptio")
                        .HasColumnType("text")
                        .HasColumnName("descriptio");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("LawyerCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lawyer_code");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Code")
                        .HasName("experiences_lawyer_pkey");

                    b.HasIndex(new[] { "LawyerCode" }, "IX_experiences_lawyer_lawyer_code");

                    b.ToTable("experiences_lawyer", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Guestaction", b =>
                {
                    b.Property<Guid>("Actionid")
                        .HasColumnType("uuid")
                        .HasColumnName("actionid");

                    b.Property<string>("Actiondata")
                        .HasColumnType("jsonb")
                        .HasColumnName("actiondata");

                    b.Property<string>("Actiontype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actiontype");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Guestid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("guestid");

                    b.Property<Guid>("Sessionid")
                        .HasColumnType("uuid")
                        .HasColumnName("sessionid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Actionid")
                        .HasName("guestactions_pkey");

                    b.ToTable("guestactions", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Guestsession", b =>
                {
                    b.Property<Guid>("Sessionid")
                        .HasColumnType("uuid")
                        .HasColumnName("sessionid");

                    b.Property<string>("Browser")
                        .HasColumnType("text")
                        .HasColumnName("browser");

                    b.Property<string>("Campaign")
                        .HasColumnType("text")
                        .HasColumnName("campaign");

                    b.Property<string>("Device")
                        .HasColumnType("text")
                        .HasColumnName("device");

                    b.Property<string>("Entryurl")
                        .HasColumnType("text")
                        .HasColumnName("entryurl");

                    b.Property<DateTime>("Firstseenat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("firstseenat");

                    b.Property<string>("Guestid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("guestid");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ipaddress");

                    b.Property<DateTime>("Lastseenat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastseenat");

                    b.Property<string>("Medium")
                        .HasColumnType("text")
                        .HasColumnName("medium");

                    b.Property<string>("Os")
                        .HasColumnType("text")
                        .HasColumnName("os");

                    b.Property<string>("Referrer")
                        .HasColumnType("text")
                        .HasColumnName("referrer");

                    b.Property<short?>("Sessionstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("sessionstatus");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Useragent")
                        .HasColumnType("text")
                        .HasColumnName("useragent");

                    b.HasKey("Sessionid")
                        .HasName("guestsessions_pkey");

                    b.ToTable("guestsessions", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Lawyer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("CommonName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("common_name");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<string>("Genner")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("genner");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Code")
                        .HasName("lawyer_pkey");

                    b.ToTable("lawyer", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.LawyerDocument", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("ContentFile")
                        .HasColumnType("text")
                        .HasColumnName("content_file");

                    b.Property<NpgsqlTsVector>("ContentVectorFile")
                        .HasColumnType("tsvector")
                        .HasColumnName("content_vector_file");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_type");

                    b.Property<string>("LawyerCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lawyer_code");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Code")
                        .HasName("lawyer_documents_pkey");

                    b.HasIndex(new[] { "LawyerCode" }, "IX_lawyer_documents_lawyer_code");

                    b.ToTable("lawyer_documents", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Logchatai", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<bool?>("Block")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("block");

                    b.Property<string>("ChataiCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chatai_code");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<bool?>("IsStorage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_storage");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Code")
                        .HasName("logchatai_pkey");

                    b.ToTable("logchatai", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Menu", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<long?>("ActiveStatus")
                        .HasColumnType("bigint")
                        .HasColumnName("active_status");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("TitleActive")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.HasKey("Code")
                        .HasName("menu_pkey");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.MenuDe", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("MenuCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_code");

                    b.Property<string>("Slug")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<string>("TypeField")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type_field");

                    b.Property<string>("TypeView")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_view");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<string>("ValueField")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value_field");

                    b.HasKey("Code")
                        .HasName("menu_des_pkey");

                    b.ToTable("menu_des", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.MenuRole", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<long?>("ActiveStatus")
                        .HasColumnType("bigint")
                        .HasColumnName("active_status");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("Display")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display");

                    b.Property<bool?>("IsCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_create");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edit");

                    b.Property<bool?>("IsView")
                        .HasColumnType("boolean")
                        .HasColumnName("is_view");

                    b.Property<string>("MenuCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_code");

                    b.Property<string>("MenuDesCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_des_code");

                    b.Property<string>("Other")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("other");

                    b.Property<string>("ParentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("TitleActive")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title_active");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("update_by");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Code")
                        .HasName("menu_role_pkey");

                    b.ToTable("menu_role", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.PracticeArea", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("AreaName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("area_name");

                    b.Property<NpgsqlTsVector>("AreaNameVector")
                        .HasColumnType("tsvector")
                        .HasColumnName("area_name_vector");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LawyerCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lawyer_code");

                    b.HasKey("Code")
                        .HasName("practice_areas_pkey");

                    b.HasIndex(new[] { "LawyerCode" }, "IX_practice_areas_lawyer_code");

                    b.ToTable("practice_areas", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.PracticeAreaCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("update_by");

                    b.HasKey("Code")
                        .HasName("practice_area_categories_pkey");

                    b.ToTable("practice_area_categories", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TokenHash" }, "IX_RefreshTokens_TokenHash");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("flag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Translations")
                        .HasColumnType("text")
                        .HasColumnName("translations");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wikiDataId")
                        .HasComment("Rapid API GeoDB Cities");

                    b.HasKey("Id")
                        .HasName("regions_pkey");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FipsCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fips_code");

                    b.Property<short>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("flag");

                    b.Property<string>("Iso2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("iso2");

                    b.Property<string>("Iso31662")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("iso3166_2");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Native")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("native");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Population")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("population");

                    b.Property<string>("Timezone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("timezone")
                        .HasComment("IANA timezone identifier (e.g., America/New_York)");

                    b.Property<string>("Translations")
                        .HasColumnType("text")
                        .HasColumnName("translations");

                    b.Property<string>("Type")
                        .HasMaxLength(191)
                        .HasColumnType("character varying(191)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wikiDataId")
                        .HasComment("Rapid API GeoDB Cities");

                    b.HasKey("Id")
                        .HasName("states_pkey");

                    b.HasIndex(new[] { "CountryId" }, "states_country_id_idx");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Subregion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("flag");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint")
                        .HasColumnName("region_id");

                    b.Property<string>("Translations")
                        .HasColumnType("text")
                        .HasColumnName("translations");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WikiDataId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wikiDataId")
                        .HasComment("Rapid API GeoDB Cities");

                    b.HasKey("Id")
                        .HasName("subregions_pkey");

                    b.HasIndex(new[] { "RegionId" }, "subregions_region_id_idx");

                    b.ToTable("subregions", (string)null);
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetRoleClaim", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserClaim", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserLogin", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUserToken", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.CategoryLawyer", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Category", "CategoryCodeNavigation")
                        .WithMany("CategoryLawyers")
                        .HasForeignKey("CategoryCode")
                        .IsRequired()
                        .HasConstraintName("category_lawyer_category_code_fkey");

                    b.Navigation("CategoryCodeNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.CertificatesLawyer", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Lawyer", "LawyerCodeNavigation")
                        .WithMany("CertificatesLawyers")
                        .HasForeignKey("LawyerCode")
                        .IsRequired()
                        .HasConstraintName("certificates_lawyer_lawyer_code_fkey");

                    b.Navigation("LawyerCodeNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.City", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("cities_country_id_fkey");

                    b.HasOne("Cms.DataNpg.Legal.EF.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired()
                        .HasConstraintName("cities_state_id_fkey");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Country", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Region", "RegionNavigation")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("countries_region_id_fkey");

                    b.HasOne("Cms.DataNpg.Legal.EF.Subregion", "SubregionNavigation")
                        .WithMany("Countries")
                        .HasForeignKey("SubregionId")
                        .HasConstraintName("countries_subregion_id_fkey");

                    b.Navigation("RegionNavigation");

                    b.Navigation("SubregionNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.EducationsLawyer", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Lawyer", "LawyerCodeNavigation")
                        .WithMany("EducationsLawyers")
                        .HasForeignKey("LawyerCode")
                        .HasConstraintName("educations_lawyer_lawyer_code_fkey");

                    b.Navigation("LawyerCodeNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.ExperiencesLawyer", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Lawyer", "LawyerCodeNavigation")
                        .WithMany("ExperiencesLawyers")
                        .HasForeignKey("LawyerCode")
                        .HasConstraintName("experiences_lawyer_lawyer_code_fkey");

                    b.Navigation("LawyerCodeNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.LawyerDocument", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Lawyer", "LawyerCodeNavigation")
                        .WithMany("LawyerDocuments")
                        .HasForeignKey("LawyerCode")
                        .HasConstraintName("lawyer_documents_lawyer_code_fkey");

                    b.Navigation("LawyerCodeNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.PracticeArea", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Lawyer", "LawyerCodeNavigation")
                        .WithMany("PracticeAreas")
                        .HasForeignKey("LawyerCode")
                        .HasConstraintName("practice_areas_lawyer_code_fkey");

                    b.Navigation("LawyerCodeNavigation");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.State", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("states_country_id_fkey");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Subregion", b =>
                {
                    b.HasOne("Cms.DataNpg.Legal.EF.Region", "Region")
                        .WithMany("Subregions")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("subregions_region_id_fkey");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Category", b =>
                {
                    b.Navigation("CategoryLawyers");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Lawyer", b =>
                {
                    b.Navigation("CertificatesLawyers");

                    b.Navigation("EducationsLawyers");

                    b.Navigation("ExperiencesLawyers");

                    b.Navigation("LawyerDocuments");

                    b.Navigation("PracticeAreas");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Region", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Subregions");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Cms.DataNpg.Legal.EF.Subregion", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
