// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class AddressUser
{
    public string Code { get; set; }

    public string TitleAddress { get; set; }

    public int RegionsId { get; set; }

    public int CountryId { get; set; }

    public int StateId { get; set; }

    public int CityId { get; set; }

    public string FullAddress { get; set; }

    public bool IsSetDefault { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool IsBlock { get; set; }

    public string UserId { get; set; }
}