// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class AspNetUserRole
{
    public string UserId { get; set; }

    public string RoleId { get; set; }
}