// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Association
{
    public string Code { get; set; }

    public string Name { get; set; }

    public string Abbreviation { get; set; }

    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public int ProvinceId { get; set; }

    public string ProvinceName { get; set; }

    public string Address { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string Website { get; set; }

    public DateOnly? EstablishedDate { get; set; }

    public string Description { get; set; }

    public string LegalAuthority { get; set; }

    public bool? Status { get; set; }

    public int? ActiveStatus { get; set; }

    public string ActiveTitle { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }
}