// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class CategoryLawyer
{
    public string Code { get; set; }

    public string LawyerCode { get; set; }

    public string CategoryCode { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Category CategoryCodeNavigation { get; set; }
}