// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Category
{
    public string Code { get; set; }

    public string Title { get; set; }

    public string Slug { get; set; }

    public string Description { get; set; }

    public string Details { get; set; }

    public string TypeField { get; set; }

    public string ValueField { get; set; }

    public bool IsShow { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string TypeView { get; set; }

    public string ParentId { get; set; }

    public string Other { get; set; }

    public int? Display { get; set; }

    public virtual ICollection<CategoryLawyer> CategoryLawyers { get; set; } = new List<CategoryLawyer>();
}