// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class CertificatesLawyer
{
    public string Code { get; set; }

    public string LawyerCode { get; set; }

    public string Title { get; set; }

    public string Slug { get; set; }

    public string IssuedBy { get; set; }

    public DateOnly? IssueDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public virtual Lawyer LawyerCodeNavigation { get; set; }
}