// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Chatai
{
    public string Code { get; set; }

    public string RoleUser { get; set; }

    public string NickName { get; set; }

    public string IpUser { get; set; }

    public string DeviceUser { get; set; }

    public string AppName { get; set; }

    public string Token { get; set; }

    public DateTime? StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public DateTime? CreateAt { get; set; }

    public bool? Status { get; set; }

    public string UserId { get; set; }
}