// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class City
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long StateId { get; set; }

    public string StateCode { get; set; }

    public long CountryId { get; set; }

    public string CountryCode { get; set; }

    public string Type { get; set; }

    public int? Level { get; set; }

    public long? ParentId { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public string Native { get; set; }

    public long? Population { get; set; }

    /// <summary>
    /// IANA timezone identifier (e.g., America/New_York)
    /// </summary>
    public string Timezone { get; set; }

    public string Translations { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public short Flag { get; set; }

    /// <summary>
    /// Rapid API GeoDB Cities
    /// </summary>
    public string WikiDataId { get; set; }

    public virtual Country Country { get; set; }

    public virtual State State { get; set; }
}