// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Contentchatai
{
    public string Code { get; set; }

    public string LogchataiCode { get; set; }

    public string ContentChat { get; set; }

    public DateTime? SendAt { get; set; }

    public string ReceiveChat { get; set; }

    public DateTime? ReceiveAt { get; set; }
}