// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class ExperiencesLawyer
{
    public string Code { get; set; }

    public string LawyerCode { get; set; }

    public string Position { get; set; }

    public string Organization { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Descriptio { get; set; }

    public virtual Lawyer LawyerCodeNavigation { get; set; }
}