// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Guestsession
{
    public Guid Sessionid { get; set; }

    public string Guestid { get; set; }

    public DateTime Firstseenat { get; set; }

    public DateTime Lastseenat { get; set; }

    public string Ipaddress { get; set; }

    public string Useragent { get; set; }

    public string Device { get; set; }

    public string Os { get; set; }

    public string Browser { get; set; }

    public string Entryurl { get; set; }

    public string Referrer { get; set; }

    public string Campaign { get; set; }

    public string Medium { get; set; }

    public string Source { get; set; }

    public short? Sessionstatus { get; set; }
}