// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Guestaction
{
    public Guid Actionid { get; set; }

    public Guid Sessionid { get; set; }

    public string Guestid { get; set; }

    public string Actiontype { get; set; }

    public string Actiondata { get; set; }

    public string Url { get; set; }

    public DateTime Createdat { get; set; }
}