// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NpgsqlTypes;

namespace Cms.DataNpg.Legal.EF;

public partial class LawyerDocument
{
    public string Code { get; set; }

    public string LawyerCode { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public string FilePath { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string ContentFile { get; set; }

    public NpgsqlTsVector ContentVectorFile { get; set; }

    public virtual Lawyer LawyerCodeNavigation { get; set; }
}