// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Lawyer
{
    public string Code { get; set; }

    public string UserId { get; set; }

    public string FullName { get; set; }

    public string CommonName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Genner { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public virtual ICollection<CertificatesLawyer> CertificatesLawyers { get; set; } = new List<CertificatesLawyer>();

    public virtual ICollection<EducationsLawyer> EducationsLawyers { get; set; } = new List<EducationsLawyer>();

    public virtual ICollection<ExperiencesLawyer> ExperiencesLawyers { get; set; } = new List<ExperiencesLawyer>();

    public virtual ICollection<LawyerDocument> LawyerDocuments { get; set; } = new List<LawyerDocument>();

    public virtual ICollection<PracticeArea> PracticeAreas { get; set; } = new List<PracticeArea>();
}