// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Cms.DataNpg.Legal.EF;

public partial class LegalDbContext : DbContext
{
    public LegalDbContext(DbContextOptions<LegalDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AddressUser> AddressUsers { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<Association> Associations { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CategoryLawyer> CategoryLawyers { get; set; }

    public virtual DbSet<CertificatesLawyer> CertificatesLawyers { get; set; }

    public virtual DbSet<Chatai> Chatais { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Contentchatai> Contentchatais { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<EducationsLawyer> EducationsLawyers { get; set; }

    public virtual DbSet<ExperiencesLawyer> ExperiencesLawyers { get; set; }

    public virtual DbSet<Guestaction> Guestactions { get; set; }

    public virtual DbSet<Guestsession> Guestsessions { get; set; }

    public virtual DbSet<Lawyer> Lawyers { get; set; }

    public virtual DbSet<LawyerDocument> LawyerDocuments { get; set; }

    public virtual DbSet<Logchatai> Logchatais { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuDe> MenuDes { get; set; }

    public virtual DbSet<MenuRole> MenuRoles { get; set; }

    public virtual DbSet<MockTrial> MockTrials { get; set; }

    public virtual DbSet<PracticeArea> PracticeAreas { get; set; }

    public virtual DbSet<PracticeAreaCategory> PracticeAreaCategories { get; set; }

    public virtual DbSet<Practicipant> Practicipants { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<ReportMockTrial> ReportMockTrials { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<Subregion> Subregions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AddressUser>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("address_user_pkey");

            entity.ToTable("address_user");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.CityId)
                .ValueGeneratedOnAdd()
                .HasColumnName("city_id");
            entity.Property(e => e.CountryId)
                .ValueGeneratedOnAdd()
                .HasColumnName("country_id");
            entity.Property(e => e.CreateAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.FullAddress)
                .HasMaxLength(500)
                .HasColumnName("full_address");
            entity.Property(e => e.IsBlock)
                .HasDefaultValue(false)
                .HasColumnName("is_block");
            entity.Property(e => e.IsSetDefault)
                .HasDefaultValue(true)
                .HasColumnName("is_set_default");
            entity.Property(e => e.RegionsId)
                .ValueGeneratedOnAdd()
                .HasColumnName("regions_id");
            entity.Property(e => e.StateId)
                .ValueGeneratedOnAdd()
                .HasColumnName("state_id");
            entity.Property(e => e.TitleAddress)
                .HasMaxLength(200)
                .HasColumnName("title_address");
            entity.Property(e => e.UserId)
                .HasMaxLength(100)
                .HasColumnName("user_id");
        });

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex").IsUnique();

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex").IsUnique();

            entity.Property(e => e.CodeUser)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.FisrtName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Image).IsRequired();
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.HasIndex(e => e.RoleId, "IX_AspNetUserRoles_RoleId");
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<Association>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("associations_pkey");

            entity.ToTable("associations");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.Abbreviation)
                .HasColumnType("character varying")
                .HasColumnName("abbreviation");
            entity.Property(e => e.ActiveStatus).HasColumnName("active_status");
            entity.Property(e => e.ActiveTitle)
                .HasMaxLength(50)
                .HasColumnName("active_title");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.ContactEmail)
                .HasMaxLength(300)
                .HasColumnName("contact_email");
            entity.Property(e => e.ContactPhone)
                .HasMaxLength(20)
                .HasColumnName("contact_phone");
            entity.Property(e => e.CountryId)
                .ValueGeneratedOnAdd()
                .HasColumnName("country_id");
            entity.Property(e => e.CountryName)
                .HasMaxLength(200)
                .HasColumnName("country_name");
            entity.Property(e => e.CreateAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("create_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EstablishedDate).HasColumnName("established_date");
            entity.Property(e => e.LegalAuthority)
                .HasMaxLength(300)
                .HasColumnName("legal_authority");
            entity.Property(e => e.Name)
                .HasMaxLength(300)
                .HasColumnName("name");
            entity.Property(e => e.ProvinceId)
                .ValueGeneratedOnAdd()
                .HasColumnName("province_id");
            entity.Property(e => e.ProvinceName)
                .HasMaxLength(200)
                .HasColumnName("province_name");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.UpdateAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("update_at");
            entity.Property(e => e.Website)
                .HasMaxLength(300)
                .HasColumnName("website");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("category_pkey");

            entity.ToTable("category");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.CreateDate).HasColumnName("create_date");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .HasColumnName("description");
            entity.Property(e => e.Details).HasColumnName("details");
            entity.Property(e => e.Display).HasColumnName("display");
            entity.Property(e => e.IsShow)
                .HasDefaultValue(true)
                .HasColumnName("is_show");
            entity.Property(e => e.Other)
                .HasMaxLength(100)
                .HasColumnName("other");
            entity.Property(e => e.ParentId)
                .HasMaxLength(100)
                .HasColumnName("parent_id");
            entity.Property(e => e.Slug)
                .HasMaxLength(300)
                .HasColumnName("slug");
            entity.Property(e => e.Title)
                .HasMaxLength(300)
                .HasColumnName("title");
            entity.Property(e => e.TypeField)
                .HasMaxLength(10)
                .HasColumnName("type_field");
            entity.Property(e => e.TypeView)
                .HasMaxLength(100)
                .HasColumnName("type_view");
            entity.Property(e => e.UpdateDate).HasColumnName("update_date");
            entity.Property(e => e.ValueField).HasColumnName("value_field");
        });

        modelBuilder.Entity<CategoryLawyer>(entity =>
        {
            entity.HasKey(e => new { e.Code, e.LawyerCode, e.CategoryCode }).HasName("category_lawyer_pkey");

            entity.ToTable("category_lawyer");

            entity.HasIndex(e => e.CategoryCode, "IX_category_lawyer_category_code");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.LawyerCode)
                .HasMaxLength(100)
                .HasColumnName("lawyer_code");
            entity.Property(e => e.CategoryCode)
                .HasMaxLength(100)
                .HasColumnName("category_code");
            entity.Property(e => e.CreateDate).HasColumnName("create_date");
            entity.Property(e => e.UpdateDate).HasColumnName("update_date");

            entity.HasOne(d => d.CategoryCodeNavigation).WithMany(p => p.CategoryLawyers)
                .HasForeignKey(d => d.CategoryCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("category_lawyer_category_code_fkey");
        });

        modelBuilder.Entity<CertificatesLawyer>(entity =>
        {
            entity.HasKey(e => new { e.Code, e.LawyerCode }).HasName("certificates_pkey");

            entity.ToTable("certificates_lawyer");

            entity.HasIndex(e => e.LawyerCode, "IX_certificates_lawyer_lawyer_code");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.LawyerCode)
                .HasMaxLength(100)
                .HasColumnName("lawyer_code");
            entity.Property(e => e.ExpiryDate).HasColumnName("expiry_date");
            entity.Property(e => e.IssueDate).HasColumnName("issue_date");
            entity.Property(e => e.IssuedBy)
                .HasMaxLength(300)
                .HasColumnName("issued_by");
            entity.Property(e => e.Slug)
                .HasMaxLength(300)
                .HasColumnName("slug");
            entity.Property(e => e.Title)
                .HasMaxLength(300)
                .HasColumnName("title");

            entity.HasOne(d => d.LawyerCodeNavigation).WithMany(p => p.CertificatesLawyers)
                .HasForeignKey(d => d.LawyerCode)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("certificates_lawyer_lawyer_code_fkey");
        });

        modelBuilder.Entity<Chatai>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("chatai_pkey");

            entity.ToTable("chatai");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.AppName)
                .HasMaxLength(300)
                .HasColumnName("app_name");
            entity.Property(e => e.CreateAt).HasColumnName("create_at");
            entity.Property(e => e.DeviceUser)
                .HasMaxLength(300)
                .HasColumnName("device_user");
            entity.Property(e => e.EndAt).HasColumnName("end_at");
            entity.Property(e => e.IpUser)
                .HasMaxLength(20)
                .HasColumnName("ip_user");
            entity.Property(e => e.NickName)
                .HasMaxLength(200)
                .HasColumnName("nick_name");
            entity.Property(e => e.RoleUser)
                .HasMaxLength(100)
                .HasColumnName("role_user");
            entity.Property(e => e.StartAt).HasColumnName("start_at");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.Token).HasColumnName("token");
            entity.Property(e => e.UserId)
                .HasMaxLength(100)
                .HasColumnName("user_id");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("cities_pkey");

            entity.ToTable("cities");

            entity.HasIndex(e => e.CountryId, "cities_country_id_idx");

            entity.HasIndex(e => e.StateId, "cities_state_id_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("country_code");
            entity.Property(e => e.CountryId).HasColumnName("country_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("'2014-01-01 12:01:01'::timestamp without time zone")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Flag)
                .HasDefaultValue((short)1)
                .HasColumnName("flag");
            entity.Property(e => e.Latitude)
                .HasPrecision(10, 8)
                .HasColumnName("latitude");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.Longitude)
                .HasPrecision(11, 8)
                .HasColumnName("longitude");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Native)
                .HasMaxLength(255)
                .HasColumnName("native");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.Population).HasColumnName("population");
            entity.Property(e => e.StateCode)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("state_code");
            entity.Property(e => e.StateId).HasColumnName("state_id");
            entity.Property(e => e.Timezone)
                .HasMaxLength(255)
                .HasComment("IANA timezone identifier (e.g., America/New_York)")
                .HasColumnName("timezone");
            entity.Property(e => e.Translations).HasColumnName("translations");
            entity.Property(e => e.Type)
                .HasMaxLength(191)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WikiDataId)
                .HasMaxLength(255)
                .HasComment("Rapid API GeoDB Cities")
                .HasColumnName("wikiDataId");

            entity.HasOne(d => d.Country).WithMany(p => p.Cities)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cities_country_id_fkey");

            entity.HasOne(d => d.State).WithMany(p => p.Cities)
                .HasForeignKey(d => d.StateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cities_state_id_fkey");
        });

        modelBuilder.Entity<Contentchatai>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("contentchatai_pkey");

            entity.ToTable("contentchatai");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.ContentChat).HasColumnName("content_chat");
            entity.Property(e => e.LogchataiCode)
                .HasMaxLength(100)
                .HasColumnName("logchatai_code");
            entity.Property(e => e.ReceiveAt).HasColumnName("receive_at");
            entity.Property(e => e.ReceiveChat).HasColumnName("receive_chat");
            entity.Property(e => e.SendAt).HasColumnName("send_at");
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("countries_pkey");

            entity.ToTable("countries");

            entity.HasIndex(e => e.RegionId, "countries_region_id_idx");

            entity.HasIndex(e => e.SubregionId, "countries_subregion_id_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AreaSqKm).HasColumnName("area_sq_km");
            entity.Property(e => e.Capital)
                .HasMaxLength(255)
                .HasColumnName("capital");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Currency)
                .HasMaxLength(255)
                .HasColumnName("currency");
            entity.Property(e => e.CurrencyName)
                .HasMaxLength(255)
                .HasColumnName("currency_name");
            entity.Property(e => e.CurrencySymbol)
                .HasMaxLength(255)
                .HasColumnName("currency_symbol");
            entity.Property(e => e.Emoji)
                .HasMaxLength(191)
                .HasColumnName("emoji");
            entity.Property(e => e.EmojiU)
                .HasMaxLength(191)
                .HasColumnName("emojiU");
            entity.Property(e => e.Flag)
                .HasDefaultValue((short)1)
                .HasColumnName("flag");
            entity.Property(e => e.Gdp).HasColumnName("gdp");
            entity.Property(e => e.Iso2)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("iso2");
            entity.Property(e => e.Iso3)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("iso3");
            entity.Property(e => e.Latitude)
                .HasPrecision(10, 8)
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .HasPrecision(11, 8)
                .HasColumnName("longitude");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Nationality)
                .HasMaxLength(255)
                .HasColumnName("nationality");
            entity.Property(e => e.Native)
                .HasMaxLength(255)
                .HasColumnName("native");
            entity.Property(e => e.NumericCode)
                .HasMaxLength(3)
                .IsFixedLength()
                .HasColumnName("numeric_code");
            entity.Property(e => e.Phonecode)
                .HasMaxLength(255)
                .HasColumnName("phonecode");
            entity.Property(e => e.Population).HasColumnName("population");
            entity.Property(e => e.PostalCodeFormat)
                .HasMaxLength(255)
                .HasColumnName("postal_code_format");
            entity.Property(e => e.PostalCodeRegex)
                .HasMaxLength(255)
                .HasColumnName("postal_code_regex");
            entity.Property(e => e.Region)
                .HasMaxLength(255)
                .HasColumnName("region");
            entity.Property(e => e.RegionId).HasColumnName("region_id");
            entity.Property(e => e.Subregion)
                .HasMaxLength(255)
                .HasColumnName("subregion");
            entity.Property(e => e.SubregionId).HasColumnName("subregion_id");
            entity.Property(e => e.Timezones).HasColumnName("timezones");
            entity.Property(e => e.Tld)
                .HasMaxLength(255)
                .HasColumnName("tld");
            entity.Property(e => e.Translations).HasColumnName("translations");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WikiDataId)
                .HasMaxLength(255)
                .HasComment("Rapid API GeoDB Cities")
                .HasColumnName("wikiDataId");

            entity.HasOne(d => d.RegionNavigation).WithMany(p => p.Countries)
                .HasForeignKey(d => d.RegionId)
                .HasConstraintName("countries_region_id_fkey");

            entity.HasOne(d => d.SubregionNavigation).WithMany(p => p.Countries)
                .HasForeignKey(d => d.SubregionId)
                .HasConstraintName("countries_subregion_id_fkey");
        });

        modelBuilder.Entity<EducationsLawyer>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("educations_lawyer_pkey");

            entity.ToTable("educations_lawyer");

            entity.HasIndex(e => e.LawyerCode, "IX_educations_lawyer_lawyer_code");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.Degree)
                .HasMaxLength(100)
                .HasColumnName("degree");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.Institution)
                .HasMaxLength(300)
                .HasColumnName("institution");
            entity.Property(e => e.LawyerCode)
                .HasMaxLength(100)
                .HasColumnName("lawyer_code");
            entity.Property(e => e.StartDate).HasColumnName("start_date");

            entity.HasOne(d => d.LawyerCodeNavigation).WithMany(p => p.EducationsLawyers)
                .HasForeignKey(d => d.LawyerCode)
                .HasConstraintName("educations_lawyer_lawyer_code_fkey");
        });

        modelBuilder.Entity<ExperiencesLawyer>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("experiences_lawyer_pkey");

            entity.ToTable("experiences_lawyer");

            entity.HasIndex(e => e.LawyerCode, "IX_experiences_lawyer_lawyer_code");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.Descriptio).HasColumnName("descriptio");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.LawyerCode)
                .HasMaxLength(100)
                .HasColumnName("lawyer_code");
            entity.Property(e => e.Organization)
                .HasMaxLength(200)
                .HasColumnName("organization");
            entity.Property(e => e.Position)
                .HasMaxLength(200)
                .HasColumnName("position");
            entity.Property(e => e.StartDate).HasColumnName("start_date");

            entity.HasOne(d => d.LawyerCodeNavigation).WithMany(p => p.ExperiencesLawyers)
                .HasForeignKey(d => d.LawyerCode)
                .HasConstraintName("experiences_lawyer_lawyer_code_fkey");
        });

        modelBuilder.Entity<Guestaction>(entity =>
        {
            entity.HasKey(e => e.Actionid).HasName("guestactions_pkey");

            entity.ToTable("guestactions");

            entity.Property(e => e.Actionid)
                .ValueGeneratedNever()
                .HasColumnName("actionid");
            entity.Property(e => e.Actiondata)
                .HasColumnType("jsonb")
                .HasColumnName("actiondata");
            entity.Property(e => e.Actiontype)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("actiontype");
            entity.Property(e => e.Createdat)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("createdat");
            entity.Property(e => e.Guestid)
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnName("guestid");
            entity.Property(e => e.Sessionid).HasColumnName("sessionid");
            entity.Property(e => e.Url).HasColumnName("url");
        });

        modelBuilder.Entity<Guestsession>(entity =>
        {
            entity.HasKey(e => e.Sessionid).HasName("guestsessions_pkey");

            entity.ToTable("guestsessions");

            entity.Property(e => e.Sessionid)
                .ValueGeneratedNever()
                .HasColumnName("sessionid");
            entity.Property(e => e.Browser).HasColumnName("browser");
            entity.Property(e => e.Campaign).HasColumnName("campaign");
            entity.Property(e => e.Device).HasColumnName("device");
            entity.Property(e => e.Entryurl).HasColumnName("entryurl");
            entity.Property(e => e.Firstseenat)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("firstseenat");
            entity.Property(e => e.Guestid)
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnName("guestid");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(64)
                .HasColumnName("ipaddress");
            entity.Property(e => e.Lastseenat)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("lastseenat");
            entity.Property(e => e.Medium).HasColumnName("medium");
            entity.Property(e => e.Os).HasColumnName("os");
            entity.Property(e => e.Referrer).HasColumnName("referrer");
            entity.Property(e => e.Sessionstatus)
                .HasDefaultValue((short)1)
                .HasColumnName("sessionstatus");
            entity.Property(e => e.Source).HasColumnName("source");
            entity.Property(e => e.Useragent).HasColumnName("useragent");
        });

        modelBuilder.Entity<Lawyer>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("lawyer_pkey");

            entity.ToTable("lawyer");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.CommonName)
                .HasMaxLength(300)
                .HasColumnName("common_name");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.Email)
                .HasMaxLength(500)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(300)
                .HasColumnName("full_name");
            entity.Property(e => e.Genner)
                .HasMaxLength(5)
                .HasColumnName("genner");
            entity.Property(e => e.Phone)
                .HasMaxLength(30)
                .HasColumnName("phone");
            entity.Property(e => e.RegistrationDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("registration_date");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("user_id");
        });

        modelBuilder.Entity<LawyerDocument>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("lawyer_documents_pkey");

            entity.ToTable("lawyer_documents");

            entity.HasIndex(e => e.LawyerCode, "IX_lawyer_documents_lawyer_code");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.ContentFile).HasColumnName("content_file");
            entity.Property(e => e.ContentVectorFile).HasColumnName("content_vector_file");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnName("create_at");
            entity.Property(e => e.FileName)
                .HasMaxLength(300)
                .HasColumnName("file_name");
            entity.Property(e => e.FilePath).HasColumnName("file_path");
            entity.Property(e => e.FileType)
                .HasMaxLength(200)
                .HasColumnName("file_type");
            entity.Property(e => e.LawyerCode)
                .HasMaxLength(100)
                .HasColumnName("lawyer_code");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");

            entity.HasOne(d => d.LawyerCodeNavigation).WithMany(p => p.LawyerDocuments)
                .HasForeignKey(d => d.LawyerCode)
                .HasConstraintName("lawyer_documents_lawyer_code_fkey");
        });

        modelBuilder.Entity<Logchatai>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("logchatai_pkey");

            entity.ToTable("logchatai");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.Block)
                .HasDefaultValue(true)
                .HasColumnName("block");
            entity.Property(e => e.ChataiCode)
                .HasMaxLength(100)
                .HasColumnName("chatai_code");
            entity.Property(e => e.CreateAt).HasColumnName("create_at");
            entity.Property(e => e.IsStorage).HasColumnName("is_storage");
            entity.Property(e => e.Title)
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("menu_pkey");

            entity.ToTable("menu");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.ActiveStatus).HasColumnName("active_status");
            entity.Property(e => e.CreateAt).HasColumnName("create_at");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.Title)
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.TitleActive)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("title_active");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");
        });

        modelBuilder.Entity<MenuDe>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("menu_des_pkey");

            entity.ToTable("menu_des");

            entity.Property(e => e.Code).HasMaxLength(100);
            entity.Property(e => e.CreateAt).HasColumnName("create_at");
            entity.Property(e => e.MenuCode)
                .HasMaxLength(100)
                .HasColumnName("menu_code");
            entity.Property(e => e.Slug)
                .HasMaxLength(250)
                .HasColumnName("slug");
            entity.Property(e => e.Title)
                .HasMaxLength(250)
                .HasColumnName("title");
            entity.Property(e => e.TypeField)
                .HasMaxLength(20)
                .HasColumnName("type_field");
            entity.Property(e => e.TypeView)
                .HasMaxLength(50)
                .HasColumnName("type_view");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");
            entity.Property(e => e.Url)
                .HasMaxLength(500)
                .HasColumnName("url");
            entity.Property(e => e.ValueField)
                .HasMaxLength(200)
                .HasColumnName("value_field");
        });

        modelBuilder.Entity<MenuRole>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("menu_role_pkey");

            entity.ToTable("menu_role");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.ActiveStatus).HasColumnName("active_status");
            entity.Property(e => e.CreateAt).HasColumnName("create_at");
            entity.Property(e => e.CreateBy)
                .HasMaxLength(100)
                .HasColumnName("create_by");
            entity.Property(e => e.Display)
                .HasMaxLength(50)
                .HasColumnName("display");
            entity.Property(e => e.IsCreate).HasColumnName("is_create");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.IsEdit).HasColumnName("is_edit");
            entity.Property(e => e.IsView).HasColumnName("is_view");
            entity.Property(e => e.MenuCode)
                .HasMaxLength(100)
                .HasColumnName("menu_code");
            entity.Property(e => e.MenuDesCode)
                .HasMaxLength(100)
                .HasColumnName("menu_des_code");
            entity.Property(e => e.Other)
                .HasMaxLength(100)
                .HasColumnName("other");
            entity.Property(e => e.ParentId)
                .HasMaxLength(100)
                .HasColumnName("parent_id");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TitleActive)
                .HasMaxLength(50)
                .HasColumnName("title_active");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");
            entity.Property(e => e.UpdateBy)
                .HasMaxLength(100)
                .HasColumnName("update_by");
            entity.Property(e => e.UserId)
                .HasMaxLength(100)
                .HasColumnName("user_id");
        });

        modelBuilder.Entity<MockTrial>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("mock_trial_pkey");

            entity.ToTable("mock_trial");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.ActiveStatus)
                .HasDefaultValue(1)
                .HasColumnName("active_status");
            entity.Property(e => e.CategoryId)
                .HasMaxLength(100)
                .HasColumnName("category_id");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("create_at");
            entity.Property(e => e.CreateBy)
                .HasMaxLength(100)
                .HasColumnName("create_by");
            entity.Property(e => e.Description)
                .HasMaxLength(300)
                .HasColumnName("description");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.StatusActive)
                .HasMaxLength(100)
                .HasDefaultValueSql("'is active'::character varying")
                .HasColumnName("status_active");
            entity.Property(e => e.Title)
                .HasMaxLength(300)
                .HasColumnName("title");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");
            entity.Property(e => e.UpdateBy)
                .HasMaxLength(100)
                .HasColumnName("update_by");
        });

        modelBuilder.Entity<PracticeArea>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("practice_areas_pkey");

            entity.ToTable("practice_areas");

            entity.HasIndex(e => e.LawyerCode, "IX_practice_areas_lawyer_code");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.AreaName)
                .HasMaxLength(300)
                .HasColumnName("area_name");
            entity.Property(e => e.AreaNameVector).HasColumnName("area_name_vector");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LawyerCode)
                .HasMaxLength(100)
                .HasColumnName("lawyer_code");

            entity.HasOne(d => d.LawyerCodeNavigation).WithMany(p => p.PracticeAreas)
                .HasForeignKey(d => d.LawyerCode)
                .HasConstraintName("practice_areas_lawyer_code_fkey");
        });

        modelBuilder.Entity<PracticeAreaCategory>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("practice_area_categories_pkey");

            entity.ToTable("practice_area_categories");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.CategoryName)
                .HasMaxLength(300)
                .HasColumnName("category_name");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("create_at");
            entity.Property(e => e.CreateBy)
                .HasMaxLength(100)
                .HasColumnName("create_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.UpdateAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("update_at");
            entity.Property(e => e.UpdateBy)
                .HasMaxLength(100)
                .HasColumnName("update_by");
        });

        modelBuilder.Entity<Practicipant>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("practicipant_pkey");

            entity.ToTable("practicipant");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.Attributes)
                .HasMaxLength(100)
                .HasColumnName("attributes");
            entity.Property(e => e.CategoryId)
                .HasMaxLength(100)
                .HasColumnName("category_id");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("create_at");
            entity.Property(e => e.MockTrialId)
                .HasMaxLength(100)
                .HasColumnName("mock_trial_id");
            entity.Property(e => e.TextEvidence).HasColumnName("text_evidence");
            entity.Property(e => e.TypeId)
                .HasMaxLength(100)
                .HasColumnName("type_id");
            entity.Property(e => e.UpdateAt).HasColumnName("update_at");
            entity.Property(e => e.UserId)
                .HasMaxLength(100)
                .HasColumnName("user_id");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasIndex(e => e.TokenHash, "IX_RefreshTokens_TokenHash");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.DeviceId).IsRequired();
            entity.Property(e => e.ReplacedByToken).IsRequired();
            entity.Property(e => e.TokenHash).IsRequired();
            entity.Property(e => e.UserId).IsRequired();
        });

        modelBuilder.Entity<Region>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("regions_pkey");

            entity.ToTable("regions");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Flag)
                .HasDefaultValue((short)1)
                .HasColumnName("flag");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Translations).HasColumnName("translations");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WikiDataId)
                .HasMaxLength(255)
                .HasComment("Rapid API GeoDB Cities")
                .HasColumnName("wikiDataId");
        });

        modelBuilder.Entity<ReportMockTrial>(entity =>
        {
            entity.HasKey(e => e.Code).HasName("report_mock_trial_pkey");

            entity.ToTable("report_mock_trial");

            entity.Property(e => e.Code)
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("create_at");
            entity.Property(e => e.TotalIsActive)
                .HasDefaultValue(0)
                .HasColumnName("total_is_active");
            entity.Property(e => e.TotalTrial)
                .HasDefaultValue(0)
                .HasColumnName("total_trial");
        });

        modelBuilder.Entity<State>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("states_pkey");

            entity.ToTable("states");

            entity.HasIndex(e => e.CountryId, "states_country_id_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CountryCode)
                .IsRequired()
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("country_code");
            entity.Property(e => e.CountryId).HasColumnName("country_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.FipsCode)
                .HasMaxLength(255)
                .HasColumnName("fips_code");
            entity.Property(e => e.Flag)
                .HasDefaultValue((short)1)
                .HasColumnName("flag");
            entity.Property(e => e.Iso2)
                .HasMaxLength(255)
                .HasColumnName("iso2");
            entity.Property(e => e.Iso31662)
                .HasMaxLength(10)
                .HasColumnName("iso3166_2");
            entity.Property(e => e.Latitude)
                .HasPrecision(10, 8)
                .HasColumnName("latitude");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.Longitude)
                .HasPrecision(11, 8)
                .HasColumnName("longitude");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Native)
                .HasMaxLength(255)
                .HasColumnName("native");
            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.Population)
                .HasMaxLength(255)
                .HasColumnName("population");
            entity.Property(e => e.Timezone)
                .HasMaxLength(255)
                .HasComment("IANA timezone identifier (e.g., America/New_York)")
                .HasColumnName("timezone");
            entity.Property(e => e.Translations).HasColumnName("translations");
            entity.Property(e => e.Type)
                .HasMaxLength(191)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WikiDataId)
                .HasMaxLength(255)
                .HasComment("Rapid API GeoDB Cities")
                .HasColumnName("wikiDataId");

            entity.HasOne(d => d.Country).WithMany(p => p.States)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("states_country_id_fkey");
        });

        modelBuilder.Entity<Subregion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("subregions_pkey");

            entity.ToTable("subregions");

            entity.HasIndex(e => e.RegionId, "subregions_region_id_idx");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Flag)
                .HasDefaultValue((short)1)
                .HasColumnName("flag");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.RegionId).HasColumnName("region_id");
            entity.Property(e => e.Translations).HasColumnName("translations");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.WikiDataId)
                .HasMaxLength(255)
                .HasComment("Rapid API GeoDB Cities")
                .HasColumnName("wikiDataId");

            entity.HasOne(d => d.Region).WithMany(p => p.Subregions)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("subregions_region_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}