// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Logchatai
{
    public string Code { get; set; }

    public string ChataiCode { get; set; }

    public string Title { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? Block { get; set; }

    public bool? IsStorage { get; set; }
}