// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class MenuRole
{
    public string Code { get; set; }

    public string MenuDesCode { get; set; }

    public string MenuCode { get; set; }

    public string ParentId { get; set; }

    public string Other { get; set; }

    public string Display { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsView { get; set; }

    public bool? IsCreate { get; set; }

    public bool? IsEdit { get; set; }

    public bool? Status { get; set; }

    public long? ActiveStatus { get; set; }

    public string TitleActive { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string CreateBy { get; set; }

    public string UpdateBy { get; set; }

    public string UserId { get; set; }
}