// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class MenuDe
{
    public string Code { get; set; }

    public string MenuCode { get; set; }

    public string Title { get; set; }

    public string Slug { get; set; }

    public string Url { get; set; }

    public string TypeField { get; set; }

    public string ValueField { get; set; }

    public string TypeView { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }
}