// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class MockTrial
{
    public string Code { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string CategoryId { get; set; }

    public DateTime? CreateAt { get; set; }

    public string CreateBy { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string UpdateBy { get; set; }

    public int? ActiveStatus { get; set; }

    public string StatusActive { get; set; }

    public bool? Status { get; set; }
}