// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Practicipant
{
    public string Code { get; set; }

    public string MockTrialId { get; set; }

    public string UserId { get; set; }

    public string TypeId { get; set; }

    public string CategoryId { get; set; }

    public string Attributes { get; set; }

    public string TextEvidence { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }
}