// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NpgsqlTypes;

namespace Cms.DataNpg.Legal.EF;

public partial class PracticeArea
{
    public string Code { get; set; }

    public string LawyerCode { get; set; }

    public string AreaName { get; set; }

    public NpgsqlTsVector AreaNameVector { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Lawyer LawyerCodeNavigation { get; set; }
}