// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class PracticeAreaCategory
{
    public string Code { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public DateTime? CreateAt { get; set; }

    public string CreateBy { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string UpdateBy { get; set; }
}