// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class RefreshToken
{
    public Guid Id { get; set; }

    public string UserId { get; set; }

    public string TokenHash { get; set; }

    public string DeviceId { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool Revoked { get; set; }

    public string ReplacedByToken { get; set; }
}