// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class ReportMockTrial
{
    public string Code { get; set; }

    public int? TotalTrial { get; set; }

    public int? TotalIsActive { get; set; }

    public DateTime? CreateAt { get; set; }
}