// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class State
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long CountryId { get; set; }

    public string CountryCode { get; set; }

    public string FipsCode { get; set; }

    public string Iso2 { get; set; }

    public string Iso31662 { get; set; }

    public string Type { get; set; }

    public int? Level { get; set; }

    public long? ParentId { get; set; }

    public string Native { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    /// <summary>
    /// IANA timezone identifier (e.g., America/New_York)
    /// </summary>
    public string Timezone { get; set; }

    public string Translations { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public short Flag { get; set; }

    /// <summary>
    /// Rapid API GeoDB Cities
    /// </summary>
    public string WikiDataId { get; set; }

    public string Population { get; set; }

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual Country Country { get; set; }
}