// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cms.DataNpg.Legal.EF;

public partial class Subregion
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Translations { get; set; }

    public long RegionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public short Flag { get; set; }

    /// <summary>
    /// Rapid API GeoDB Cities
    /// </summary>
    public string WikiDataId { get; set; }

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();

    public virtual Region Region { get; set; }
}